services:
  - type: web
    name: municipal-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn municipal_tax.wsgi --log-file -
    envVars:
      - key: FRONTEND_URL
        value: "https://municipal-frontend-seven.vercel.app"
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        value: "municipal-backend.onrender.com"
        sync: false
      - key: DJANGO_SECRET_KEY
        value: "23423267acf27ff0e64251b92a7137b7"
        sync: false
      - key: DATABASE_URL
        value: "postgresql://municipal_db_xi0j_user:icYrMOsKZaksXc9md8M18osqttbdx9Q9@dpg-d6i77775r7bs73fb4p7g-a/municipal_db_xi0j"
        sync: false
